### ISSUE TITLE
Not able to commit

### ISSUE THREAD

**Issue by guiyep** [stefanzweifel/git-auto-commit-action#198]
While running the girhub action on release I get the next error:

```[detached HEAD 6800b9f] [CI] publish new bundle size
 Author: guiyep <guiyep@gmail.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Actions:

```name: Release

on:
  release:
    types: [published]

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn

      - run: yarn build-prod

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn bundle-size

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] publish new bundle size"
          commit_user_name: Guillermo Polit
          commit_user_email: guiyep@gmail.com
          commit_author: guiyep <guiyep@gmail.com>
```

Any idea?
What it is only failing is the `stefanzweifel/git-auto-commit-action@v4` section

**Comment by stefanzweifel** [comment]
Thanks for reporting. For now, I've reset v4 to alias to v4.12.0.
Will have to investigate this further.

**Comment by stefanzweifel** [comment]
> fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

This is the problem. You have to checkout a branch in the actions/checkout step. (On the release trigger, GitHub Actions doesn't know which branch to checkout)

Add ref: main to the checkout step. (See docs https://github.com/actions/checkout)

**Comment by guiyep** [comment]
I wonder what is publishing my action then :) let me try!

**Comment by guiyep** [comment]
It is defaulting to master already.

**Comment by stefanzweifel** [comment]
@guiyep Hm. Could you add `branch` to the `auto-commit-action`-step?

```diff
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
+         branch: master
          commit_message: "[CI] publish new bundle size"
          commit_user_name: Guillermo Polit
          commit_user_email: guiyep@gmail.com
          commit_author: guiyep <guiyep@gmail.com>
```

**Comment by guiyep** [comment]
let me give a try! thanks for the help :)

**Comment by guiyep** [comment]
worked! thanks for the help :)
